### PR TITLE
Port package to Pharo 9

### PR DESCRIPTION
**Pull request by terpon**
Hi, 

I took a look at LDAP and I had to fix a few things before it worked on Pharo 9.

- package was using a ConfiguratioOf instead of a BaselineOf. From what I understand, versioning is managed by git and the baseline is for dependencies and platform specifics.
- an extra package LDAP-Filters has somehow popped out containing a duplicata of the core classes. It fails to load in iceberg because of Filters tag in LDAP package.
- Integer>>digitLength was removed. Use bytesCount intead.
- tests still expect a LDAP server on localhost with write permissions. One test is still failing (BERTest>>testAddRequest)

Ideally, there should be a branch or tag v1.7 at this current SHA d8f505b34dd2489eb29f61cf85512eb943b35e5a so that users can still easily get that version.

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks a lot this is super great!!!

**Comment by Ducasse** [comment]
I'm off for some days I will try to have a look.

**Comment by Ducasse** [comment]
Sorry for the delay :( I was in another universe. 
Let me know if you need help with baseline. 
I do not know exactly LDAP so I cannot really help there.

**Comment by terpon** [comment]
No problem, there was no hurry.

I don't think there will be issues right now with the baseline. There are no outside dependencies, the code uses Zinc for socket streams and SSL.

I'm learning Spec2 to try to do a LDAP browser now.

**Comment by Ducasse** [comment]
Thanks! Well Spec2.0 doc .... is a clear missing part. We will slowly starts to write one but I'm kind of burnt with it.

**Pull request merged**
